CREATE DATABASE QLNS;
USE QLNS;
CREATE TABLE PhongBan
(
    MaPB CHAR(10) NOT NULL,
    TenPB NVARCHAR(20) NOT NULL,
    DiaChi NVARCHAR(30) NOT NULL,
    SDT CHAR(12),
    CONSTRAINT pk_MaPB PRIMARY KEY(MaPB),
);
CREATE TABLE TrinhDoHocVan
(
    MaTDHV CHAR(10) NOT NULL,
    TenTD NVARCHAR(20) NOT NULL,
    ChuyenNganh NVARCHAR(20),
    CONSTRAINT pk_MaTDHV PRIMARY KEY(MaTDHV),
);
CREATE TABLE Luong
(
    MaLuong CHAR(10) NOT NULL,
    LuongCoBan FLOAT NOT NULL,
    PhuCap FLOAT,
    HeSoLuong FLOAT NOT NULL,
    CONSTRAINT pk_MaLuong PRIMARY KEY(MaLuong),
    CONSTRAINT ck_HeSoLuong CHECK(HeSoLuong>0),
);
CREATE TABLE NhanVien
(
    MaNV CHAR(10) NOT NULL,
    HoTen NVARCHAR(30) NOT NULL,
    NgaySinh DATE NOT NULL,
    GioiTinh BIT NOT NULL,
    QueQuan NVARCHAR(30) NOT NULL,
    SDT CHAR(12),
    MaPB CHAR(10) NOT NULL,
    MaTDHV CHAR(10) NOT NULL,
    MaLuong CHAR(10) NOT NULL,
    CONSTRAINT pk_MaNV PRIMARY KEY(MaNV),
    CONSTRAINT ck_NgaySinh CHECK(NgaySinh<getDate()),
    CONSTRAINT fk_MaPB FOREIGN KEY(MaPB) REFERENCES PhongBan,
    CONSTRAINT fk_MaTDHV FOREIGN KEY(MaTDHV) REFERENCES TrinhDoHocVan,
    CONSTRAINT fk_MaLuong FOREIGN KEY(MaLuong) REFERENCES Luong,

);
CREATE TABLE ChucVu
(
    MaCV CHAR(10) NOT NULL,
    TenCV NVARCHAR(20) NOT NULL,
    CONSTRAINT pk_MaCV PRIMARY KEY(MaCV),

);
CREATE TABLE NhanVien_ChucVu
(
    MaNV CHAR(10) NOT NULL,
    MaCV CHAR(10) NOT NULL,
    ThoiGianCongTac FLOAT,
    CONSTRAINT fk_MaNV FOREIGN KEY(MaNV) REFERENCES NhanVien,
    CONSTRAINT fk_MaCV FOREIGN KEY(MaCV) REFERENCES ChucVu,
    CONSTRAINT ck_TGCT check(ThoiGianCongTac>=0),
    CONSTRAINT pk_MaNV_MaCV PRIMARY KEY(MaNV,MaCV),
);
SELECT HoTen,MaNV FROM NhanVien
WHERE QueQuan='Ha Noi';
SELECT *FROM NhanVien;
SELECT MaNV,HoTen,NgaySinh FROM NhanVien
WHERE QueQuan='Ha Noi';
SELECT * FROM NhanVien
WHERE GioiTinh=1;
INSERT INTO NhanVien
VALUES('V01','Nguyen Van A','1','1998-01-08','Ha Noi','01657377877','PB01','DHTT','LCB04');
SELECT MaNV, HoTen,Sum(LuongCoBan*HeSoLuong+PhuCap)[Tổng Lương] 
FROM NhanVien INNER JOIN Luong ON NhanVien.MaLuong=Luong.MaLuong GROUP BY MaNV;

SELECT *FROM PhongBan
ORDER BY MaPB ASC;
SELECT *FROM NhanVien
WHERE YEAR(NgaySinh) <=(SELECT YEAR(NgaySinh) FROM NhanVien);
